name: Deploy Katino to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: KatinoUI

      - name: Build Angular
        run: npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"
        working-directory: KatinoUI

      - name: Show dist (debug)
        run: |
          find dist -maxdepth 5 -type f -name "index.html" -print
          ls -la dist
          ls -la dist/* || true
          ls -la dist/*/* || true
        working-directory: KatinoUI

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: KatinoUI/dist/KatinoUI   # <-- поменяй на .../browser если debug это покажет
          force_orphan: true